### ISSUE TITLE
Help wanted - List of available gallery parameters we can pass in as json

### ISSUE THREAD

**Issue by matt-harris** [variar/grav-plugin-unitegallery#10]
Two questions...

Is there a list of available gallery parameters we can pass in as json in the twig file? I had a look on the unite gallery site and wanted to try and implement extra padding. I tried this...

`{{ unite_gallery(page.media.images, '{"gallery_theme":"tiles", "tiles_type":"justified", "theme_gallery_padding":10}') }}`

But it didn't work.

The second question - is there any way of increasing the size of the small thumbnails? Currently they are around 180px.

Thanks for the great grav plugin.

**Comment by variar** [comment]
Hi,

Json parameters should be passed "as is" to unite gallery js without any modifications. Might be some bug. Could you provide generated html code where unite gallery js function is called?

As for thumbnails size this plugin generates original images for thumbnails, their size can be specified in plugin parameters. However, I think final size might be calucated automatically depending on gallery theme and width.

**Comment by variar** [comment]
I've tried your sample with json padding and it worked. Try set padding to some insane value (for example, 200) to check if it is passed to further to js

**Comment by matt-harris** [comment]
Hi,

I have updated the unite plugin and cleared Grav cache but still no luck? This is the code I'm using and gallery js function.

`  <div class="block-gallery__container">
    {{ unite_gallery(page.media.images, '{"tiles_type":"justified", "theme_gallery_padding":10}') }}
  </div>`

`  <div class="block-gallery__container">
    <div id="unite-gallery" style="display:none;">
<img alt="" data-description="" src="/images/d/f/5/4/5/df545be14534e92a43c2948b070da992cc41d4d0.jpg" data-image="/user/pages/01.home/_gallery/image01.jpg">
<img alt="" data-description="" src="/images/c/2/a/5/c/c2a5c44e5347544810627f7c290ef44cb164a76f.jpg" data-image="/user/pages/01.home/_gallery/image02.jpg">
<img alt="" data-description="" src="/images/1/7/3/7/d/1737d15b130090bc36c54069aaec064dad28f50e.jpg" data-image="/user/pages/01.home/_gallery/image03.jpg">
<img alt="" data-description="" src="/images/2/a/c/6/f/2ac6ffa9511fea1bea0e386d6f5171c3d0b3b4bf.jpg" data-image="/user/pages/01.home/_gallery/image04.jpg">
<img alt="" data-description="" src="/images/d/d/2/0/6/dd206309e6feb42da69e38d20c8fd7e72d9540ba.jpg" data-image="/user/pages/01.home/_gallery/image05.jpg">
<img alt="" data-description="" src="/images/9/1/a/c/c/91acc695178a0c02a994886f8f58b695a1fbb732.jpg" data-image="/user/pages/01.home/_gallery/image06.jpg">
<img alt="" data-description="" src="/images/6/4/b/d/8/64bd8739890df8c0f1510c8d4b1b7751eb630127.jpg" data-image="/user/pages/01.home/_gallery/image07.jpg">
<img alt="" data-description="" src="/images/0/2/5/f/0/025f0d413745e8c1c6b40a690e4df9a32749bb05.jpg" data-image="/user/pages/01.home/_gallery/image08.jpg">
<img alt="" data-description="" src="/images/e/d/7/3/0/ed730d4f9ed8f8d366d028f815d8bfaf081bbc79.jpg" data-image="/user/pages/01.home/_gallery/image09.jpg">
</div>
<script type="text/javascript">
              jQuery(document).ready(function(){
                jQuery("#unite-gallery").unitegallery({"tiles_type":"justified","theme_gallery_padding":10,"gallery_theme":"tiles"});
              });
        </script>

  </div>`

cheers

**Comment by variar** [comment]
According to generated html all parameters are passed to unitegallery as expected. Try set some extreme padding value (200-300) to see if it works.

**Comment by matt-harris** [comment]
Hey @variar all seems to work with a larger value. I will close the issue. Thanks for looking into it!
