### ISSUE TITLE
Plugin outputs raw HTML with Gantry Templates 

### ISSUE THREAD

**Issue by marcodeluca** [variar/grav-plugin-unitegallery#15]
Hi,

Was happy to find this plugin but struggling to get it working with gantry templates. The plugin is outputting raw HTML to the page: http://dev.khr.creativelogic.io/page-with-gallery

If I switch to the antimatter template, it works just fine. Any suggestions?

**Comment by marcodeluca** [comment]
ok solved. with gantry, the output of your gallery.html.twig file as suggested wasn't rendering the HTML properly. So if you adjust that file to the following, it works:

Note the change is to include: |raw

```
<div class="modular-row gallery-container {{ page.header.class }}">
	{{ unite_gallery(page.media.images)|raw }}
</div>
```

**Comment by variar** [comment]
Thanks, added this to readme.
