### ISSUE TITLE
Multiple galleries in Blog

### ISSUE THREAD

**Issue by rplCloud** [variar/grav-plugin-unitegallery#21]
Hi Anton,

I try to intergrade several galleries into one Blog post. The Blog is based on the [Quark Theme](https://github.com/getgrav/grav-theme-quark).

I tried your modular examples and the [Page Inject Plugin](https://github.com/getgrav/grav-plugin-page-inject). Unfortunately this works only once per page.

Do you have a solution for the problem?

Regards,
Reto

**Comment by rplCloud** [comment]
Hi all,

After a lot of try and error I found the following solution:

Create a config file for this plugin:
```bash
cd '<HTDOCS>/grav/user/config/plugins'
cp '<HTDOCS>/grav/user/plugins/unitegallery/unitegallery.yaml' '.'
vi 'unitegallery.yaml'
```

Content:
```yaml
enabled: true
assets_in_meta: true
gallery_theme: tiles
gallery_div_id: unite-gallery
thumb_width: 500
thumb_height: 500
```

Provide a modular twig file for the gallery:
```bash
vi '<HTDOCS>/grav/user/themes/quark/templates/modular/gallery.html.twig'
```

Content:
```twig
<div class="modular-row gallery-container {{ page.header.class }}">
    {{ unite_gallery(page.media.images,
        '{"gallery_theme":"' ~ page.header.unitegallery.gallery_theme ~ '"}',
        page.header.unitegallery.gallery_id) }}
</div>
```

Create a gallery within the Blog directory:
```bash
cd '<HTDOCS>/grav/user/blog/article1'
mkdir '_gallery-my_photos_1'
vi '_gallery-my_photos_1/gallery.md'
```

Content:
```
---
title: Gallery

unitegallery:
    gallery_id: gallery-my_photos_1
    gallery_theme: tiles
---
```

Copy the images into the directory `_gallery-my_photos_1`.

Meta data can be defined for every file (e.g. for a image called `image1.jpg`):
```bash
vi '_gallery-my_photos_1/image1.jpg.meta.yaml'
```

Content:
```yaml
alt_text: "is used for alt attribute"
description: "is used for data-description attribute"
```

Inject the gallery in the Blog article:
```bash
vi '<HTDOCS>/grav/user/blog/article1/item.md'
```

Configuration part:
```yaml
page-inject:
    active: true
    processed_content: true
```

Content part:
```markdown
[plugin:page-inject](_gallery-my_photos_1)
```

Clear caches
```bash
cd '<HTDOCS>/grav'
bin/grav clearcache
```

Regards,
Reto

**Comment by variar** [comment]
Thank you for detailed solution.

**Comment by rplCloud** [comment]
Thank you for this very nice plugin!
