### ISSUE TITLE
Add custom ID names to enable more than one gallery on a page

### ISSUE THREAD

**Issue by MrMacStripe** [variar/grav-plugin-unitegallery#5]
At the moment there is no way to add several galleries into one page. I´d like to add galleries based on folders (that would be no problem), but the custom ID feature doesn´t change when rendered, even if you put gallery_div_id into the json options.

**Comment by variar** [comment]
Hi, thanks for the suggestion. I've implemented it in d6f9d82270f968ecef11095169bf439ed8a994e7. Should be in v1.1.1. Could you please test if it does the right thing?

**Comment by variar** [comment]
Added additional json parameter `grav_gallery_div_id`. Should work in v1.1.2

**Comment by MrMacStripe** [comment]
I´m sorry for the late reply. Thank you very much, that is exactly what I had in mind.

**Comment by variar** [comment]
Hi, I'll make another issue to track this "display only images that contain this string" suggestion #6.
