### ISSUE TITLE
Page-specific Gallery Type

### ISSUE THREAD

**Issue by Brailyn** [variar/grav-plugin-unitegallery#7]
I'd like to use different types of galleries for different pages.

Is there any way I can add twig for one page only? I tried with the gallery_id in the json string, but need some help.

`{{ unite_gallery(page.media.images, '{"gallery_theme":"compact","grav_gallery_div_id":"gallery2"}') }}`

**Comment by variar** [comment]
Hi,
Have you tried to specify gallery type in page header and use that in twig. Something like this should work:

gallery.html.twig
```
<div class="modular-row gallery-container {{ page.header.class }}">
	{{ unite_gallery(page.media.images, {"gallery_theme":"page.header.unitegallery.gallery_theme"}, page.header.unitegallery.gallery_id) }}
</div>
```

page1
```
---
title: Gallery1
unitegallery:
  gallery_theme: compact
  gallery_id: gallery1
---

```

page2
```
---
title: Gallery2
unitegallery:
  gallery_theme: tiles
  gallery_id: gallery2
---
```

**Comment by Brailyn** [comment]
Thank you. Unfortunately, I am getting an error on all pages with galleries now...

`"An exception has been thrown during the rendering of a template ("json_decode() expects parameter 1 to be string, array given")."`

I added `gallery_type: THEME` before the `gallery_id: ID` line in the `modular.md` files.

I tried passing the ID in the JSON string and there error went away... but the galleries dissapeared.

```
<div class="modular-row gallery-container {{ page.header.class }}">
     {{ unite_gallery(page.media.images, '{"gallery_theme":"page.header.unitegallery.gallery_theme", "tiles_type":"justified","grav_gallery_div_id":"page.header.unitegallery.gallery_id"}') }}
</div>
```

**Comment by variar** [comment]
My bad, should have tried this on my test site first. Page header variables can't be referenced from inside strings. One should make gallery options string using explicit concatenation. This is a bit more cumbersome, but works:

```
<div class="modular-row gallery-container {{ page.header.class }}">
     {{ unite_gallery(page.media.images,
           '{"gallery_theme":"' ~ page.header.unitegallery.gallery_theme ~ '"}', page.header.unitegallery.gallery_id) }}
</div>
```

**Comment by variar** [comment]
Created a demo site with both modular and non-modular examples: https://github.com/variar/grav_example_unitegallery
