### ISSUE TITLE
Is it possible to use this plugin in a non-modular template?

### ISSUE THREAD

**Issue by ganar** [variar/grav-plugin-unitegallery#9]
I want to add this plugin on blog item page, and created a special template just for the pages with galleries. The plugin seems to load, but it generates this JS error:

```
Uncaught TypeError: jQuery(...).unitegallery is not a function
    at HTMLDocument.<anonymous> (design:153)
    at i (jquery-2.x.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.x.min.js:2)
    at Function.ready (jquery-2.x.min.js:2)
    at HTMLDocument.J (jquery-2.x.min.js:2)
```
Neither the CSS nor the JS seems to load in the header. Any help is appreciated

**Comment by variar** [comment]
Hi, could you post the template that you are using?

**Comment by ganar** [comment]
Yes [it is twentyfifteen](https://github.com/getgrav/grav-theme-twentyfifteen)

**Comment by ganar** [comment]
I did a change on the `item.html.twig` substituting the top image for the gallery, in the same way that you document here.

That produced an empty space with the divs for the gallery and the JS that initializes it, but no CSS or JS at the top. .

In the end I followed the instructions you gave for a modular page and it did work.

**Comment by variar** [comment]
This might be somehow connected with #8. I'll try to setup test site with twentyfifteen and see if modular/non-modular page processing differs.

**Comment by variar** [comment]
Added crude fix in 1.1.3 version and some documentation (3cc50f2764a5f01026bd62f379d3a0a742ab65fb). Please check it out.

**Comment by variar** [comment]
Try adding assets_in_meta: true to unitegallery configuration in page header. It should be true by default, but in my local testing I've always set in explicitly in page header.

**Comment by ganar** [comment]
¡Yes! It must be a bug: that did it for us. Galleries are working

**Comment by variar** [comment]
Tested on fresh install and it worked as expected without assets_in_meta: true in page header. Added extra note to readme. Closing for now.
